# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: none

pool:
  name: Default

steps:
- task: Npm@1
  displayName: 'Install npm'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install newman -g'

- task: Npm@1
  displayName: 'Install html report'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g newman-reporter-htmlextra'
  
- script: 'newman run TesteApi-develop.postman_collection -e develop.postman_environment.json -r htmlextra --reporters cli,junit,json,htmlextra --reporter-junit-export junitReport.xml --reporter-htmlextra-export TestReport.html'
  displayName: 'Run test with report'

- task: MaciejMaciejewski.postman-report.UploadPostmanHtmlReport.UploadPostmanHtmlReport@1
  displayName: 'Upload Postman Html Report'
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results '
  inputs:
    testResultsFiles: '**/*.xml'
    testRunTitle: Results