# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: none

pool:
  name: Default

steps:
# Install Newman
- task: Npm@1
  displayName: 'Install Newman'
  inputs:
    command: 'install'
    verbose: false
    customCommand: '-g newman'

# Install HTML Reporter for Newman
- task: Npm@1
  displayName: 'Install HTML Reporter'
  inputs:
    command: 'install'
    verbose: false
    customCommand: '-g newman-reporter-htmlextra'

# Install JUnit Merge Tool
- task: Npm@1
  displayName: 'Install JUnit Merge Tool'
  inputs:
    command: 'install'
    verbose: false
    customCommand: '-g junit-merge'

# Verify installations
- powershell: |
    npm list -g newman 
    npm list -g newman-reporter-htmlextra  
    npm list -g junit-merge 
    node -v
  displayName: 'Check Installations'

# Run Newman tests with specific configurations
- powershell: |
    npx newman run 01_usuarios.postman_collection.json -e develop.postman_environment.json -g workspace.postman_globals.json --delay-request 1 -r cli,junit,json,htmlextra --reporter-junit-export junitReport1.xml --reporter-htmlextra-export tests_users.html
    npx newman run 02_login.postman_collection.json -e develop.postman_environment.json -g workspace.postman_globals.json --delay-request 1 -r cli,junit,json,htmlextra --reporter-junit-export junitReport2.xml --reporter-htmlextra-export tests_login.html
  displayName: 'Run tests'
  continueOnError: true

# Merge JUnit reports into one
- script: |
    junit-merge junitReport1.xml junitReport2.xml -o mergedJunitReport.xml
  displayName: 'Merge JUnit Reports'
  continueOnError: true

# Upload HTML reports
- task: MaciejMaciejewski.postman-report.UploadPostmanHtmlReport.UploadPostmanHtmlReport@1
  displayName: 'Upload Merged Postman HTML Report'
  inputs:
    reportFile: 'tests_users.html tests_login.html'
  continueOnError: true

# Publish JUnit test results
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '**/mergedJunitReport.xml'
    testRunTitle: 'Postman Test Results'